# Generated by Django 3.2.8 on 2021-12-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='location',
            new_name='current_location',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='emailid',
            new_name='emailid_primary',
        ),
        migrations.AddField(
            model_name='contact',
            name='emailid_secondary',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='salary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
