# Generated by Django 3.2.8 on 2021-12-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0002_auto_20211222_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='salary',
        ),
    ]
