# Generated by Django 3.2.8 on 2021-12-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0003_remove_contact_salary'),
    ]

    operations = [
        migrations.RunSQL("update contacts_app_field set name = 'emailid_primary' where name = 'emailid' ")
    ]
