# Generated by Django 3.2.8 on 2022-01-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0005_locationupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notice_period',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
