# Generated by Django 3.2.8 on 2022-01-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0006_contact_notice_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='key_skills_secondary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
